# Generated by Django 5.0.6 on 2024-06-19 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(1, 0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
