# Generated by Django 5.0.6 on 2024-06-19 12:47

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Required. Category's name", max_length=150)),
                ('image', models.ImageField(default='/defaults/category-default.jpg', upload_to=api.models.Category.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Required. Product's name", max_length=150)),
                ('price', models.FloatField(help_text="Required. Product's price", validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(blank=True, help_text="Product's description")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='/defaults/product-default.jpg', upload_to=api.models.ProductImage.upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
    ]
