# Generated by Django 5.0.6 on 2024-06-20 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Publication time of product'),
            preserve_default=False,
        ),
    ]
